#    security.ignored=true
#    security.basic.enabled=false


spring:
    liquibase:
        enabled: false
    sql:
        init:
            mode: always
    application:
        name: SupplyWarehouse-J8-SB2
    datasource:
        tomcat:
            testOnBorrow: true
            validationQuery: "SELECT 1"
        url: "jdbc:postgresql://localhost:5432/supply_warehouse_db01?ssl=false"
        username: supply_warehouse
        password: 234q586
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: none # none = disable Hibernate create the schema
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    devtools:
        add-properties: false
        livereload:
            port: 35730
            enabled: false

logging:
    config: "config/log4j2.yaml"

supply.warehouse.config:
    simple-debug: true
    working-data: D:\MyDocsTeng-workDoc\github-SupplyWarehouse-J8-SB2\workData\work
    dump-requests: true
    dump-data: D:\MyDocsTeng-workDoc\github-SupplyWarehouse-J8-SB2\workData\dump
    registration-callback: http://localhost:8071/fake/callback/clientRegistration
    task-a: 1
    scheduler:
        lookup-new-certificate-response: 0/4 * * * * *
    #    temp-task-bravo: 0/40 * * * * *
    #    temp-task-delta: 0/40 * * * * *

server:
    port: 8071
